[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[markup.goldmark.renderer]
  unsafe = true

[frontmatter]
  _merge = 'deep'
[outputformats]
  _merge = 'deep'
[outputs]
  _merge = 'deep'

[outputFormats.presentation]
  baseName = "presentation"
  mediaType = "text/html"
  notAlternative = false
  permalinkable = true
  isHTML = true

[[cascade]]
  _merge = 'deep'
  outputs = ['presentation']
  [cascade._target]
    path = '/publication/**'