name = "sligo"
license = "MIT"
licenselink = "https://github.com/lowdit/sligo/blob/master/LICENSE"
description = "Publish a simple presentation with MarkDown Frontmatter"
homepage = "https://github.com/lowdit/sligo"
tags = ["report"]
features = ["Presentation"]
[author]
    name = "Bertrand Keller"
    homepage = "https://bertrandkeller.info"